# .manver.toml

commit_msg_tpl = "release({identifier}): bump {name} {prev_version} -> {next_version}"
bump_strategy = "conventional_commits"

[projects]

[projects.manver]
version = "0.3.0"  #: manver

files = [
  {path = "manver/__init__.py", pattern = '__version__ ?= ?"(.*?)"'},
  {path = "pyproject.toml", pattern = 'version ?= ?"(.*?)"'},
  {path = "tests/test_manver.py", pattern = '__version__ ?== ?"(.*?)"'},
]
