repos:
  - repo: local
    hooks:
    - name: black
      id: black
      language: system
      entry: poetry run black
      types_or: [python, pyi]

    - name: isort
      id: isort
      language: system
      entry: poetry run isort
      args: ['--filter-files']
      require_serial: true
      types_or: [cython, pyi, python]

    - name: flake8
      id: flake8
      language: system
      entry: poetry run flake8
      require_serial: true
      types: [python]
