name: 'bump semver anywhere - action'
description: 'Bump your semantic version of any software using regex'
inputs:
  id:
    description: 'which identifier to bump'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/scratchmex/manver'
  args:
    - 'bump'
    - '--yes'
    - '--id'
    - ${{ inputs.id }}
