# bump_semver_anywhere.toml

[general]
current_version = "0.3.0"

[vcs]
commit = true
commit_msg = "release({part}): bump {current_version} -> {new_version}"

[files]

[files.python-module]
filename = "bump_semver_anywhere/__init__.py"
pattern = '__version__ ?= ?"(.*?)"'

[files.python-pyproject]
filename = "pyproject.toml"
pattern = 'version ?= ?"(.*?)"'

[files.python-pytest]
filename = "tests/test_bump_semver_anywhere.py"
pattern = '__version__ ?== ?"(.*?)"'
