name: Bump version
on:
  issue_comment:
    types: [created, edited]
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - name: handle comment with Comvent
      uses: rytswd/comvent@v0.4.5
      id: comvent
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        config-path: .github/comvent-manver-setup.yaml

    - name: Checkout the latest code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: run manver
      uses: scratchmex/manver@main
      with:
        id: ${{ steps.comvent.outputs.manver-command }}

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
